/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tela;

import javax.swing.JOptionPane;

/**
 *
 * @author limalinux
 */
public class JanelaPrincipalTeste extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public JanelaPrincipalTeste() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public javax.swing.JButton getBotaoEditarCidade() {
		return botaoEditarCidade;
	}

	public void setBotaoEditarCidade(javax.swing.JButton botaoEditarCidade) {
		this.botaoEditarCidade = botaoEditarCidade;
	}

	public javax.swing.JButton getBotaoExcluirCidade() {
		return botaoExcluirCidade;
	}

	public void setBotaoExcluirCidade(javax.swing.JButton botaoExcluirCidade) {
		this.botaoExcluirCidade = botaoExcluirCidade;
	}

	public javax.swing.JButton getBotaoFazerRelatorio() {
		return botaoFazerRelatorio;
	}

	public void setBotaoFazerRelatorio(javax.swing.JButton botaoFazerRelatorio) {
		this.botaoFazerRelatorio = botaoFazerRelatorio;
	}

	public javax.swing.JButton getBotaoInserirCidade() {
		return botaoInserirCidade;
	}

	public void setBotaoInserirCidade(javax.swing.JButton botaoInserirCidade) {
		this.botaoInserirCidade = botaoInserirCidade;
	}

	public javax.swing.JButton getBotaoInserirRegistro() {
		return botaoInserirRegistro;
	}

	public void setBotaoInserirRegistro(javax.swing.JButton botaoInserirRegistro) {
		this.botaoInserirRegistro = botaoInserirRegistro;
	}

	public javax.swing.JButton getBotaoPesquisar() {
		return botaoPesquisar;
	}

	public void setBotaoPesquisar(javax.swing.JButton botaoPesquisar) {
		this.botaoPesquisar = botaoPesquisar;
	}

	public javax.swing.JTextField getCampoDeTextoCodigo() {
		return campoDeTextoCodigo;
	}

	public void setCampoDeTextoCodigo(javax.swing.JTextField campoDeTextoCodigo) {
		this.campoDeTextoCodigo = campoDeTextoCodigo;
	}

	public javax.swing.JTextField getCampoDeTextoContatosNovos() {
		return campoDeTextoContatosNovos;
	}

	public void setCampoDeTextoContatosNovos(javax.swing.JTextField campoDeTextoContatosNovos) {
		this.campoDeTextoContatosNovos = campoDeTextoContatosNovos;
	}

	public javax.swing.JTextField getCampoDeTextoEmpresa() {
		return campoDeTextoEmpresa;
	}

	public void setCampoDeTextoEmpresa(javax.swing.JTextField campoDeTextoEmpresa) {
		this.campoDeTextoEmpresa = campoDeTextoEmpresa;
	}

	public javax.swing.JTextField getCampoDeTextoEndereco() {
		return campoDeTextoEndereco;
	}

	public void setCampoDeTextoEndereco(javax.swing.JTextField campoDeTextoEndereco) {
		this.campoDeTextoEndereco = campoDeTextoEndereco;
	}

	public javax.swing.JTextField getCampoDeTextoNumeroLogradouro() {
		return campoDeTextoNumeroLogradouro;
	}

	public void setCampoDeTextoNumeroLogradouro(javax.swing.JTextField campoDeTextoNumeroLogradouro) {
		this.campoDeTextoNumeroLogradouro = campoDeTextoNumeroLogradouro;
	}

	public javax.swing.JTextArea getCampoTextoAreaObservacoes() {
		return campoTextoAreaObservacoes;
	}

	public void setCampoTextoAreaObservacoes(javax.swing.JTextArea campoTextoAreaObservacoes) {
		this.campoTextoAreaObservacoes = campoTextoAreaObservacoes;
	}

	public javax.swing.JTextField getCampoTextoBairro() {
		return campoTextoBairro;
	}

	public void setCampoTextoBairro(javax.swing.JTextField campoTextoBairro) {
		this.campoTextoBairro = campoTextoBairro;
	}

	public javax.swing.JTextField getCampoTextoCep() {
		return campoTextoCep;
	}

	public void setCampoTextoCep(javax.swing.JTextField campoTextoCep) {
		this.campoTextoCep = campoTextoCep;
	}

	public javax.swing.JTextField getCampoTextoCodigoCidade() {
		return campoTextoCodigoCidade;
	}

	public void setCampoTextoCodigoCidade(javax.swing.JTextField campoTextoCodigoCidade) {
		this.campoTextoCodigoCidade = campoTextoCodigoCidade;
	}

	public javax.swing.JTextField getCampoTextoContatosDesligados() {
		return campoTextoContatosDesligados;
	}

	public void setCampoTextoContatosDesligados(javax.swing.JTextField campoTextoContatosDesligados) {
		this.campoTextoContatosDesligados = campoTextoContatosDesligados;
	}

	public javax.swing.JTextField getCampoTextoDescricaoCidade() {
		return campoTextoDescricaoCidade;
	}

	public void setCampoTextoDescricaoCidade(javax.swing.JTextField campoTextoDescricaoCidade) {
		this.campoTextoDescricaoCidade = campoTextoDescricaoCidade;
	}

	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        javax.swing.JPanel painelDeFundo = new javax.swing.JPanel();
        labelempresa = new javax.swing.JLabel();
        campoDeTextoEmpresa = new javax.swing.JTextField();
        labelContatosNovos = new javax.swing.JLabel();
        labelObservacoes = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        campoDeTextoContatosNovos = new javax.swing.JTextField();
        labelContatosDesligados = new javax.swing.JLabel();
        campoTextoContatosDesligados = new javax.swing.JTextField();
        labelEndereco = new javax.swing.JLabel();
        campoDeTextoEndereco = new javax.swing.JTextField();
        campoDeTextoNumeroLogradouro = new javax.swing.JTextField();
        labelNumeroLogradouro = new javax.swing.JLabel();
        labelBairro = new javax.swing.JLabel();
        campoTextoBairro = new javax.swing.JTextField();
        labelcep = new javax.swing.JLabel();
        campoTextoCep = new javax.swing.JTextField();
        labelCidade = new javax.swing.JLabel();
        campoTextoCodigoCidade = new javax.swing.JTextField();
        campoTextoDescricaoCidade = new javax.swing.JTextField();
        botaoInserirCidade = new javax.swing.JButton();
        botaoEditarCidade = new javax.swing.JButton();
        botaoExcluirCidade = new javax.swing.JButton();
        labelTextoCodigo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoTextoAreaObservacoes = new javax.swing.JTextArea();
        botaoInserirRegistro = new javax.swing.JButton();
        botaoFazerRelatorio = new javax.swing.JButton();
        labelData = new javax.swing.JLabel();
        labelA = new javax.swing.JLabel();
        botaoPesquisar = new javax.swing.JButton();
        campoDeTextoCodigo = new javax.swing.JTextField();
        campoDeTextoCodigo.setText("1");

       
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
       
        setTitle("Contatos - Dark Mode Edition");
       
        
//        setLocation(new java.awt.Point(400, 300));
//        setLocationByPlatform(true);
        
        
        setPreferredSize(new java.awt.Dimension(940, 760));

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        labelempresa.setText("Empresa");

        campoDeTextoEmpresa.setBackground(new java.awt.Color(243, 219, 88));

        labelContatosNovos.setText("Contatos Novos");

        labelObservacoes.setText("Observações");

        campoDeTextoContatosNovos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDeTextoContatosNovosActionPerformed(evt);
            }
        });

        labelContatosDesligados.setText("Contatos Desligados");

        campoTextoContatosDesligados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoContatosDesligadosActionPerformed(evt);
            }
        });

        labelEndereco.setText("Endereço");

        labelNumeroLogradouro.setText("Nº");

        labelBairro.setText("Bairro");

        labelcep.setText("CEP");

        labelCidade.setText("Cidade");

        campoTextoCodigoCidade.setBackground(new java.awt.Color(62, 146, 199));
        campoTextoCodigoCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoCodigoCidadeActionPerformed(evt);
            }
        });

        botaoInserirCidade.setText("Inserir Cidade");
        botaoInserirCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInserirCidadeActionPerformed(evt);
            }
        });

        botaoEditarCidade.setText("Editar cidade");

        botaoExcluirCidade.setText("Excluir Cidade");

        labelTextoCodigo.setText("Código");

        campoTextoAreaObservacoes.setColumns(20);
        campoTextoAreaObservacoes.setRows(5);
        jScrollPane1.setViewportView(campoTextoAreaObservacoes);

        botaoInserirRegistro.setText("Inserir Registro");
        botaoInserirRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInserirRegistroActionPerformed(evt);
            }
        });

        botaoFazerRelatorio.setText("Fazer o Relatório");
        botaoFazerRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFazerRelatorioActionPerformed(evt);
            }
        });

        labelData.setText("Data");

        labelA.setText("Á");

        botaoPesquisar.setText("Pesquisar");

        campoDeTextoCodigo.setEditable(false);
        campoDeTextoCodigo.setEnabled(false);
        campoDeTextoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDeTextoCodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelDeFundoLayout = new javax.swing.GroupLayout(painelDeFundo);
        painelDeFundo.setLayout(painelDeFundoLayout);
        painelDeFundoLayout.setHorizontalGroup(
            painelDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDeFundoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(painelDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDeFundoLayout.createSequentialGroup()
                        .addGroup(painelDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelDeFundoLayout.createSequentialGroup()
                                .addComponent(labelCidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(campoTextoCodigoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(campoTextoDescricaoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(146, 146, 146))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDeFundoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botaoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelDeFundoLayout.createSequentialGroup()
                                .addComponent(labelNumeroLogradouro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoDeTextoNumeroLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(labelBairro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoTextoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(labelcep)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoTextoCep, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(24, 24, 24))
                    .addGroup(painelDeFundoLayout.createSequentialGroup()
                        .addComponent(labelContatosDesligados)
                        .addGap(18, 18, 18)
                        .addComponent(campoTextoContatosDesligados))
                    .addGroup(painelDeFundoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(painelDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelObservacoes)
                            .addGroup(painelDeFundoLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(botaoInserirRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(botaoFazerRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(botaoEditarCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(painelDeFundoLayout.createSequentialGroup()
                                    .addComponent(labelData)
                                    .addGap(359, 359, 359)
                                    .addComponent(labelA, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(painelDeFundoLayout.createSequentialGroup()
                        .addComponent(labelContatosNovos)
                        .addGap(18, 18, 18)
                        .addComponent(campoDeTextoContatosNovos))
                    .addGroup(painelDeFundoLayout.createSequentialGroup()
                        .addComponent(labelempresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoDeTextoEmpresa))
                    .addGroup(painelDeFundoLayout.createSequentialGroup()
                        .addComponent(labelEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoDeTextoEndereco))))
            .addGroup(painelDeFundoLayout.createSequentialGroup()
                .addGroup(painelDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDeFundoLayout.createSequentialGroup()
                        .addGroup(painelDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelDeFundoLayout.createSequentialGroup()
                                .addGap(352, 352, 352)
                                .addComponent(labelTextoCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoDeTextoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelDeFundoLayout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addGroup(painelDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDeFundoLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(botaoExcluirCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(painelDeFundoLayout.createSequentialGroup()
                                        .addComponent(botaoInserirCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(339, 339, 339)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDeFundoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        painelDeFundoLayout.setVerticalGroup(
            painelDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDeFundoLayout.createSequentialGroup()
                .addGroup(painelDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTextoCodigo)
                    .addComponent(campoDeTextoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDeTextoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelempresa))
                .addGap(18, 18, 18)
                .addGroup(painelDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDeTextoContatosNovos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelContatosNovos))
                .addGap(18, 18, 18)
                .addGroup(painelDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelContatosDesligados)
                    .addComponent(campoTextoContatosDesligados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDeTextoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEndereco))
                .addGap(18, 18, 18)
                .addGroup(painelDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDeTextoNumeroLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNumeroLogradouro)
                    .addComponent(labelBairro)
                    .addComponent(campoTextoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelcep)
                    .addComponent(campoTextoCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTextoDescricaoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTextoCodigoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCidade)
                    .addComponent(botaoPesquisar))
                .addGap(18, 18, 18)
                .addGroup(painelDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoExcluirCidade)
                    .addComponent(botaoEditarCidade)
                    .addComponent(botaoInserirCidade))
                .addGap(42, 42, 42)
                .addGroup(painelDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelData)
                    .addComponent(labelA))
                .addGap(41, 41, 41)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(labelObservacoes)
                .addGroup(painelDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDeFundoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(painelDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoInserirRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoFazerRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74))
                    .addGroup(painelDeFundoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(41, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(painelDeFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(painelDeFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 943, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void botaoFazerRelatorioActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    	
    }                                                   

    private void botaoInserirRegistroActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
    }                                                    

    private void campoDeTextoCodigoActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void botaoInserirCidadeActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void campoTextoCodigoCidadeActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        // TODO add your handling code here:
    }                                                      

    private void campoTextoContatosDesligadosActionPerformed(java.awt.event.ActionEvent evt) {                                                             
        // TODO add your handling code here:
    }                                                            

    private void campoDeTextoContatosNovosActionPerformed(java.awt.event.ActionEvent evt) {                                                          
        // TODO add your handling code here:
    }                                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipalTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipalTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipalTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipalTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipalTeste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton botaoEditarCidade;
    private javax.swing.JButton botaoExcluirCidade;
    private javax.swing.JButton botaoFazerRelatorio;
    private javax.swing.JButton botaoInserirCidade;
    private javax.swing.JButton botaoInserirRegistro;
    private javax.swing.JButton botaoPesquisar;
    private javax.swing.JTextField campoDeTextoCodigo;
    private javax.swing.JTextField campoDeTextoContatosNovos;
    private javax.swing.JTextField campoDeTextoEmpresa;
    private javax.swing.JTextField campoDeTextoEndereco;
    private javax.swing.JTextField campoDeTextoNumeroLogradouro;
    private javax.swing.JTextArea campoTextoAreaObservacoes;
    private javax.swing.JTextField campoTextoBairro;
    private javax.swing.JTextField campoTextoCep;
    private javax.swing.JTextField campoTextoCodigoCidade;
    private javax.swing.JTextField campoTextoContatosDesligados;
    private javax.swing.JTextField campoTextoDescricaoCidade;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelA;
    private javax.swing.JLabel labelBairro;
    private javax.swing.JLabel labelCidade;
    private javax.swing.JLabel labelContatosDesligados;
    private javax.swing.JLabel labelContatosNovos;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelEndereco;
    private javax.swing.JLabel labelNumeroLogradouro;
    private javax.swing.JLabel labelObservacoes;
    private javax.swing.JLabel labelTextoCodigo;
    private javax.swing.JLabel labelcep;
    private javax.swing.JLabel labelempresa;
    private javax.swing.JSeparator separador;
    // End of variables declaration                   
}
